# Generated by Django 4.2.1 on 2023-05-03 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginrRole',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecomerce.basemodel')),
                ('role_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'login_role',
            },
            bases=('ecomerce.basemodel',),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecomerce.basemodel')),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('account_hoder', models.CharField(max_length=100)),
                ('mail_id', models.EmailField(max_length=200)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField()),
                ('profil_url', models.URLField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('login_count', models.IntegerField(blank=True, default=0, null=True)),
                ('is_acc_lock', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('role_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomerce.loginrrole')),
            ],
            options={
                'db_table': 'account_detail',
            },
            bases=('ecomerce.basemodel',),
        ),
    ]
