# Generated by Django 4.2.1 on 2023-05-03 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecomerce.basemodel')),
                ('bill_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('disc_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'invoice',
            },
            bases=('ecomerce.basemodel',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecomerce.basemodel')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('amount_net', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Product',
            },
            bases=('ecomerce.basemodel',),
        ),
        migrations.RenameModel(
            old_name='LoginrRole',
            new_name='LoginRole',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='account_hoder',
            new_name='account_holder',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='address',
            new_name='del_address',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='profil_url',
            new_name='profile_url',
        ),
        migrations.AlterField(
            model_name='account',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='mail_id',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecomerce.basemodel')),
                ('amount_net', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_type', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('Bank', 'Bank')], max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomerce.invoicedetails')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomerce.product')),
            ],
            options={
                'db_table': 'purchase',
            },
            bases=('ecomerce.basemodel',),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomerce.account'),
        ),
    ]
